name: Publish CLI

on:
  push:
    branches:
      - dev_ci

jobs:
  publish-cli:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest" # for Arm based macs (M1 and above).
            target: "aarch64-apple-darwin"
          - platform: "macos-latest" # for Intel based macs.
            target: "x86_64-apple-darwin"

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Rust cache
        uses: swatinem/rust-cache@v2

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Build
        run: cargo build ${{ matrix.args }} --target ${{ matrix.target }} --release

      - name: Rename Unix
        run: mv target/${{ matrix.target }}/release/librespot librespot-cli-${{ matrix.target }}
        if: contains(matrix.platform, 'macos')

      - name: Upload Unix
        run: gh release upload nightly librespot-cli-${{ matrix.target }} --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: contains(matrix.platform, 'macos')
